version: "3"
services:
  app:
    restart: always
    build: .
    env_file:
      - .env
    ports:
    - 5000:5000
    volumes:
    - .:/app
    depends_on:
    - postgres
    links:
    - postgres:postgres
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: "testdb"
    #    volumes:
    #    - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432