version: "3"
services:
#  frontend:
#    build:
#      context: ./frontend/my-app
#      dockerfile: Dockerfile
#    volumes:
#    - '.:/usr/src/app'
#    - '/usr/src/app/node_modules'
#    ports:
#    - '4200:4200'
#    depends_on:
#    - postgres
#    - app
#    links:
#    - app:app
  app:
    restart: always
    build: .
    env_file:
      - .env
    ports:
    - 5000:5000
    volumes:
    - .:/app
    depends_on:
    - postgres
    links:
      # This means link this container's "postgres" domain to their container's postgres domain (ip)
    - postgres:postgres
  postgres:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: "testdb"
    #    volumes:
    #    - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432