version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: kumarcal/basics:flask-ml-app
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet: